version: '3.7'

services:
  controller:
    build: .
    volumes:
      - "../volume:/app/volume"
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=false
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
        window: 60s