version: '3.3'

services:
  controller:
    build: .
    ports:
      - 8081:8081
    network_mode: host
    volumes:
      - "../volume:/app/volume"
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=false